### PR TITLE
Fix #448  Word break for few cases - Sihari, Bihari, etc.

### LINKED ISSUE #448: Mobile Issue. Broken Matra in Lariwar Assist view
image

Please observe Sihari is broken. The last Shabad should appear only when it is complete, else should follow in next line.

@bogas04 @ManjotS @saintsoldierx

### PR DESCRIPTION
**Pull request by bogas04**
… side matras along with Bindi, Mukta - Many are left

* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
its not complete yet...
See comment under #448

**Comment by bogas04** [comment]
Yup, can you uncheck it in the branch itself?

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
please pull and test - Both Punjabi and Unicode

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
Please review.

File: src/js/components/Larivaar/util.js [hunk 1]
```diff
@@ -0,0 +1,108 @@
+import React from 'react';
+
+const matrasThatAppearAtRightSideOfChar = "wIuUyYoOW"
+const halfCharThatAppearAtRightSideOfChar = "Í´R@˜®"
+const nasalSoundCaharacter = "NMµ"
+const sihari = "i";
+const allMatrasHalfCharAndNasalSoundChar = sihari + matrasThatAppearAtRightSideOfChar + halfCharThatAppearAtRightSideOfChar + nasalSoundCaharacter
+const unicodeMatras = "ਾਿੀੁੂੇੈੋੌੰਂ"
+
+export function fixLarivaar(word, unicode, larivaarAssistColor, indexVal) {
```
Comment (bogas04) [inline src/js/components/Larivaar/util.js]: Since we are returning JSX array, maybe we should make this a component. 

```jsx
<LarivaarWord unicode={unicode} larivaarAssist={larivaarAssist}>{val}</LarivaarWord>
```

File: src/js/components/Larivaar/util.js [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+        } else {
+            breakSupportedCharList.push(
+                <span key={indexVal+"."+i} style={{ color: indexVal % 2 === 1 ? larivaarAssistColor : '' }}>
+                    <span key={i}>
+                    {segmentedValArr[i]}<wbr />
+                    </span>
+                </span>
+            )
+        }
+    }
```
Comment (bogas04) [inline src/js/components/Larivaar/util.js]: can you refactor this to use [Array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)?

```jsx
const Characters = segmentedValArray
  .map(value => (
    value.includes("´")
      ?   <span key={i} className = "wordBreakSpecialChar">
            {segmentedValArr[i]}<wbr />
            </span>
  ))
  
```

File: src/js/components/Larivaar/util.js [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+		if(!isUnicodeConsonant(str[i+1])) {
+			arrWordBreak.push(segmentedStr)
+			segmentedStr = '';
+		}
+	}
+    return arrWordBreak
+}
+
+function isConsonant(char) {
+	if(allMatrasHalfCharAndNasalSoundChar.indexOf(char) == -1) {
```
Comment (bogas04) [inline src/js/components/Larivaar/util.js]: you can simply `return allMatrasHalfCharAndNasalSoundChar.indexOf(char) === -1`

File: src/js/components/Larivaar/util.js [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+		return true;
+	} else {
+		return false;
+	}
+}
+
+function isUnicodeConsonant(char) {
+	if(unicodeMatras.indexOf(char) != -1) {
```
Comment (bogas04) [inline src/js/components/Larivaar/util.js]: You can simply `return unicodeMatras.indexOf(char) !== -1`

File: src/js/components/Larivaar/util.js [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+		return true;
+	} else {
+		return false;
+	}
+}
+
+function isSihari(char) {
+	if(char == sihari) {
```
Comment (bogas04) [inline src/js/components/Larivaar/util.js]: you can simply `return char === sihari`

File: src/js/components/RenderPromise.js [hunk 6]
```diff
@@ -17,7 +17,7 @@ export default class RenderPromise extends React.PureComponent {
     this.executePromise(this.props.promise);
   }
 
-  componentWillReceiveProps (newProps) {
+  static getDerivedStateFromProps (newProps) {
```
Comment (bogas04) [inline src/js/components/RenderPromise.js]: This wouldn't work as we are in a static function. I think `componentDidUpdate` is the right place to do this.

File: src/js/pages/Search/Layout.js [hunk 7]
```diff
@@ -12,7 +12,7 @@ import {
 } from '../../util/analytics';
 import Controls, { supportedMedia } from '../../components/Controls';
 import GenericError, { SachKaur } from '../../components/GenericError';
-import Larivaar from '../../components/Larivaar';
+import Larivaar from '../../components/Larivaar/index';
```
Comment (bogas04) [inline src/js/pages/Search/Layout.js]: No need to add index.

File: src/scss/_panktee.scss [hunk 8]
```diff
@@ -3,10 +3,14 @@
     margin-bottom: -0.25rem;
 
     &.larivaar {
-      word-break: break-all;
+      // word-break: break-all;
```
Comment (bogas04) [inline src/scss/_panktee.scss]: Remove this css block entirely if it's not used.

File: src/scss/_panktee.scss [hunk 9]
```diff
@@ -3,10 +3,14 @@
...
     }
   }
 
+  .wordBreakSpecialChar {
```
Comment (bogas04) [inline src/scss/_panktee.scss]: Can we use some descriptive name? `larivaar-word-breaker` ?

File: src/js/components/BaaniLine.js [hunk 10]
```diff
@@ -1,6 +1,6 @@
 import React from 'react';
 import PropTypes from 'prop-types';
-import Larivaar from './Larivaar';
+import Larivaar from './Larivaar/index';
```
[the remark this answers is not in the document]
Comment (harpreetkhalsagtbit) [reply src/js/components/BaaniLine.js]: Done

File: src/js/components/Larivaar/util.js (hunk 2 above)
Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: Done

File: src/js/components/Larivaar/util.js (hunk 3 above)
Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: Regarding: use of filter, map, reduce

I have to skip some iterations to group some characters, in that case i have to use *continue* that i can't do with reduce, map, filter. 

Any suggestion?

File: src/js/components/Larivaar/util.js (hunk 4 above)
Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: donr

File: src/js/components/Larivaar/util.js (hunk 5 above)
Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: done

File: src/js/pages/Search/Layout.js (hunk 7 above)
Comment (harpreetkhalsagtbit) [reply src/js/pages/Search/Layout.js]: Done

File: src/scss/_panktee.scss (hunk 8 above)
Comment (harpreetkhalsagtbit) [reply src/scss/_panktee.scss]: Done

File: src/scss/_panktee.scss (hunk 9 above)
Comment (harpreetkhalsagtbit) [reply src/scss/_panktee.scss]: Actually its just for one special character where <wbr> (word break html gets break LOL)
Thats why I used wordBreakSPecialChar.
Any suggestion?

File: src/js/components/RenderPromise.js (hunk 6 above)
Comment (harpreetkhalsagtbit) [reply src/js/components/RenderPromise.js]: I will discuss this with you to understand it completely as of now, you suggest what is correct i will change it accordingly

Comment (harpreetkhalsagtbit) [reply src/js/components/RenderPromise.js]: you want me to change it to `componentDidUpdate`?
```js
  componentDisUpdate (newProps) {
    this.executePromise(newProps.promise);
  }
```

File: src/scss/_panktee.scss (hunk 9 above)
Comment (bogas04) [reply src/scss/_panktee.scss]: Maybe you can use inline style for this.

File: src/js/components/RenderPromise.js (hunk 6 above)
Comment (bogas04) [reply src/js/components/RenderPromise.js]: `this.props` will be newProps

File: src/js/components/Larivaar/util.js (hunk 3 above)
Comment (bogas04) [reply src/js/components/Larivaar/util.js]: You can continue in reduce by returning same value.

Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: Done

Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: reverted.... buggy implementation
Unable to skip next iteration.

Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: I think bug was already there in my code even before using reduce. Let me fix.

**Comment by bogas04** [comment]
@harpreetkhalsagtbit I'm sorry I couldn't give time lately.

Could you please resolve the conflicts and fix the bug you were talking about?

Thanks a lot for your seva jee!

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
Unable to merge dev
getting this error

screen shot 2018-06-16 at 1 25 57 pm

**Comment by harpreetkhalsagtbit** [comment]
Fixed: merge issue
FIxed via online github  conflict resolver

File: src/scss/_panktee.scss (hunk 9 above)
Comment (harpreetkhalsagtbit) [reply src/scss/_panktee.scss]: DOne

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
Please have a fresh review on everything

File: src/js/components/BaaniLine.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (bogas04) [reply src/js/components/BaaniLine.js]: @harpreetkhalsagtbit I think it wasn't committed.

File: src/js/pages/Search/Layout.js [hunk 11]
```diff
@@ -117,10 +117,7 @@ class Layout extends React.PureComponent {
                   >
                     {unicode ? (
                       <div className="unicode">
-                        <Larivaar
-                          larivaarAssist={larivaarAssist}
-                          enable={larivaar}
-                        >
+                        <Larivaar larivaarAssist={larivaarAssist} enable={larivaar} unicode={unicode}>
```
Comment (bogas04) [inline src/js/pages/Search/Layout.js]: Could you please use prettier?

File: src/js/pages/Search/Layout.js (hunk 7 above)
Comment (bogas04) [reply src/js/pages/Search/Layout.js]: I think it wasn't committed.

File: src/js/components/Larivaar/util.js (hunk 5 above)
Comment (bogas04) [reply src/js/components/Larivaar/util.js]: I think it wasn't committed

File: src/js/components/Larivaar/util.js (hunk 4 above)
Comment (bogas04) [reply src/js/components/Larivaar/util.js]: I think it wasn't committed

File: src/js/components/Larivaar/util.js (hunk 3 above)
Comment (bogas04) [reply src/js/components/Larivaar/util.js]: Could you please use prettier on the files you modified?

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
I don't understand how but i can see my changes got reverted. Will fix all

File: src/js/components/Larivaar/util.js (hunk 5 above)
Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: Done

File: src/js/pages/Search/Layout.js (hunk 7 above)
Comment (harpreetkhalsagtbit) [reply src/js/pages/Search/Layout.js]: Done

File: src/js/components/Larivaar/util.js (hunk 4 above)
Comment (harpreetkhalsagtbit) [reply src/js/components/Larivaar/util.js]: Done

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
Please review all again

**Comment by bogas04** [comment]
@harpreetkhalsagtbit could you please review my changes? Thank you so much! Also I'm sorry I couldn't check the PR earlier.
